#!/usr/bin/python3

from FruitBowl import FruitBowl
from time import sleep

fb = FruitBowl()
sleep(2)
fb.show_contents()
sleep(2)
fb.add_single("orange")
sleep(2)
fb.show_contents()
sleep(2)
fb.add_single("banana")
sleep(2)
fb.show_contents()
sleep(2)
fb.add_multiple("lemon",4)
sleep(2)
fb.show_contents()
sleep(2)
fb.add_multiple("grape", 300)
sleep(2)
fb.show_contents()
sleep(2)
fb.take_item("lemon")
sleep(2)
fb.show_contents()
sleep(2)
fb.take_item("orange")
sleep(2)
fb.show_contents()
sleep(2)
fb.take_item("orange")
sleep(2)
fb.show_contents()
sleep(2)
fb.add_single("python")
sleep(2)
fb.show_contents()
sleep(2)
fb.add_single("python")
sleep(2)
fb.show_contents()
sleep(2)